apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backtest-ing
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.backtest.casa
    secretName: backtest-tls
  rules:
    - host: api.backtest.casa
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: backtest-svc
                port:
                  number: 8080
