apiVersion: apps/v1
kind: Deployment
metadata:
  name: backtest-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backtest
  template:
    metadata:
      labels:
        app: backtest
    spec:
      containers:
        - name: backtest
          image: kostorub/backtest:latest
          # resources:
          #   limits:
          #     memory: "100M"
          #     cpu: "100m"
          #   requests:
          #     memory: "100M"
          #     cpu: "100m"
          ports:
            - containerPort: 8080
          volumeMounts:
          - mountPath: "/var/sqlite"
            name: sqlite-v
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: sqlite-v
          persistentVolumeClaim:
            claimName: sqlite-pvc
